repos:
- repo: local
  hooks:
  - id: pdm-format
    name: pdm format
    entry: pdm format
    language: python
    pass_filenames: false
    types: [ python ]
  - id: pdm-test
    name: pdm test
    entry: pdm test
    language: python
    pass_filenames: false
    types: [ python ]
