name: Deploy MkDocs

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.9.23
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.23"

      - name: Install pdm
        run: pip install pdm==2.25.2

      - name: Install MkDocs toolchain
        run: pdm install

      - name: Build documentation
        run: pdm mkdocs-build

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to VPS
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -e rsync -avz --delete ./site/ \
            root@${{ secrets.SSH_HOST }}:/var/www/vhosts/simonwaiblinger.de/rustico.simonwaiblinger.de/httpdocs/
